chore(deps): Update grok and dependencies (#7176)
* chore(deps): Update grok and dependencies

This updates grok to 1.1 and its dependencies.

I couldn't upgrade to 1.2 due to a conflict with lucet on `userfaultfd`:

```
error: failed to select a version for `userfaultfd`.
    ... required by package `lucet-runtime-internals v0.7.0-dev (https://github.com/bytecodealliance/lucet.git?rev=b1863dacc8c92c11e5434fc8815d9b9a26cfe3db#b1863dac)`
    ... which is depended on by `lucet-runtime v0.7.0-dev (https://github.com/bytecodealliance/lucet.git?rev=b1863dacc8c92c11e5434fc8815d9b9a26cfe3db#b1863dac)`
    ... which is depended on by `lucet-wasi v0.7.0-dev (https://github.com/bytecodealliance/lucet.git?rev=b1863dacc8c92c11e5434fc8815d9b9a26cfe3db#b1863dac)`
    ... which is depended on by `vector v0.13.0 (/Users/jesse.szwedko/workspace/vector)`
versions that meet the requirements `^0.2.0` are: 0.2.1, 0.2.0
```

This required adding additional build dependencies to the cross and Windows builds: `llvm` and `clang`.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
Co-authored-by: anubhavg-icpl <anubhavg@infopercept.com>