chore(ci): Upgrade to cross 0.2.5 (#16527)
* chore(ci): Upgrade to cross 0.2.5

Curious to see if this resolves recent issues we've seen around

```
 /cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.2/src/sys/memfd.rs:56: undefined reference to `memfd_create'
          collect2: error: ld returned 1 exit status
```

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

* Missed one

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

---------

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>
Co-authored-by: anubhavg-icpl <anubhavg@infopercept.com>